APPLICATION_STARTUP = "APPLICATION_STARTUP"
APPLICATION_READY = "APPLICATION_READY"

MATCH_STARTED = "MATCH_STARTED"
MATCH_COMPLETED = "MATCH_COMPLETED"
MATCH_FAILED = "MATCH_FAILED"

TASK_STARTED = "TASK_STARTED"
TASK_COMPLETED = "TASK_COMPLETED"
TASK_FAILED = "TASK_FAILED"

OPEN_JOBS_FETCHED = "OPEN_JOBS_FETCHED"
RESUMES_FETCHED = "RESUMES_FETCHED"
MATCHES_PREPARED = "MATCHES_PREPARED"
RESUME_NOT_FOUND = "RESUME_NOT_FOUND"
JOB_NOT_FOUND = "JOB_NOT_FOUND"
DATABASE_ROLLBACK = "DATABASE_ROLLBACK"
READINESS_CHECK_PASSED = "READINESS_CHECK_PASSED"
READINESS_CHECK_FAILED = "READINESS_CHECK_FAILED"

LIVENESS_CHECK = "LIVENESS_CHECK"
celery_worker_ready = "CELERY_WORKER_READY"